# Generated by Django 5.1 on 2024-09-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0004_remove_record_userprofile_alter_album_artist_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="records",
            field=models.ManyToManyField(related_name="records", to="albums.record"),
        ),
    ]
