# Generated by Django 5.1 on 2024-09-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_userprofile_records"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="records",
        ),
    ]
