# Generated by Django 5.1 on 2024-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.RenameField(
            model_name="album",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="record",
            old_name="is_favorite",
            new_name="is_loved",
        ),
        migrations.RemoveField(
            model_name="album",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="record",
            name="img_url",
        ),
        migrations.RemoveField(
            model_name="record",
            name="num_stars",
        ),
        migrations.RemoveField(
            model_name="record",
            name="source_uri",
        ),
        migrations.AddField(
            model_name="album",
            name="spotify_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="is_future",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="artist",
            name="spotify_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="spotify_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="album",
            name="artist",
        ),
        migrations.AlterField(
            model_name="album",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="genres",
            field=models.ManyToManyField(to="albums.genre"),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotify_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration", models.IntegerField()),
                ("number", models.IntegerField()),
                ("source_url", models.URLField(blank=True, null=True)),
                ("artist", models.ManyToManyField(to="albums.artist")),
            ],
            options={
                "verbose_name": "Track",
                "verbose_name_plural": "Tracks",
            },
        ),
        migrations.AddField(
            model_name="album",
            name="tracks",
            field=models.ManyToManyField(to="albums.track"),
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ManyToManyField(to="albums.artist"),
        ),
    ]
