# Generated by Django 5.1 on 2024-09-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0002_genre_rename_title_album_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="rating",
        ),
        migrations.AlterField(
            model_name="album",
            name="genres",
            field=models.ManyToManyField(related_name="genres", to="albums.genre"),
        ),
        migrations.AlterField(
            model_name="album",
            name="tracks",
            field=models.ManyToManyField(related_name="tracks", to="albums.track"),
        ),
    ]
