# Generated by Django 5.1 on 2024-09-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0003_remove_album_rating_alter_album_genres_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="userprofile",
        ),
        migrations.AlterField(
            model_name="album",
            name="artist",
            field=models.ManyToManyField(related_name="albums", to="albums.artist"),
        ),
        migrations.AlterField(
            model_name="record",
            name="album",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="albums.album",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="artist",
            field=models.ManyToManyField(related_name="artists", to="albums.artist"),
        ),
    ]
