# Generated by Django 5.1 on 2024-09-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0004_remove_record_userprofile_alter_album_artist_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="spotify_url",
            new_name="source_url",
        ),
        migrations.RemoveField(
            model_name="album",
            name="source_uri",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="is_future",
        ),
        migrations.AddField(
            model_name="album",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="is_explicit",
            field=models.BooleanField(default=False),
        ),
    ]
