# Generated by Django 5.1 on 2024-09-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0005_rename_spotify_url_artist_source_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="copyright",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
