# Generated by Django 5.1 on 2024-09-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0006_album_copyright"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="popularity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
