# Generated by Django 5.1 on 2024-09-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0007_album_label_album_popularity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="duration",
            new_name="duration_ms",
        ),
        migrations.RenameField(
            model_name="track",
            old_name="number",
            new_name="track_number",
        ),
    ]
