# Generated by Django 5.1 on 2024-09-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0008_rename_duration_track_duration_ms_and_more"),
        ("user", "0003_remove_userprofile_records"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="track_number",
            new_name="number",
        ),
        migrations.AddField(
            model_name="record",
            name="userprofile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="user.userprofile",
            ),
            preserve_default=False,
        ),
    ]
