# Generated by Django 5.1 on 2024-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0009_rename_track_number_track_number_record_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="number",
        ),
        migrations.AddField(
            model_name="track",
            name="track_number",
            field=models.IntegerField(default=1),
        ),
    ]
