# Generated by Django 5.1 on 2024-09-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0010_remove_track_number_track_track_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="albums.album",
            ),
        ),
    ]
